allow_anonymous true
listener 1883
set_tcp_nodelay true
max_inflight_messages 0
max_queued_messages 0
persistence false
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
